[params]
  keywords = "Ric, artist, unknown, Fritz Neumann, JCB"
  description = "This blog tries to help to solve the mystery „Who was Ric?“"
  menuTitleShort = "Ric"
  logo = "/images/logo.png"
  svgIcon = "/images/favicon.svg"
  stylesheets = ["https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap"]
  linkTumblr = true
  hideTitle = false
  hideListTitle = true
  widePosts = true
  enableImageViewer = true
  enablePDFViewer = false
  copyrightYears = "MMXXI - MMXXVI"
  wikidata = false
  disableScale = true

[params.author]
  email = 'mail@christianmahnke.de'
  name = 'Christian Mahnke'
  uri = 'http://www.wikidata.org/entity/Q137668638'
